name: Node CI

on:
  push:
    branches:
      - main
      - sdk-automation/models
      - promote/main
  pull_request:
    branches:
      - main
      - sdk-automation/models
      - promote/main
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  node-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Print Node version
        run: node --version
      - name: npm install
        run: npm install
      - name: Lint code
        run: npm run lint:fix && npm run lint
      - name: Build project
        run: npm run build

  node-test:
    runs-on: ubuntu-latest
    needs: node-build

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Print Node version
        run: node --version
      - name: npm install
        run: npm install
      - name: Run tests
        run: npm test
      - name: Run tests with coverage
        run: npm run test:coverage

  node-sonarcloud:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
    needs: node-test

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
